apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "switchyard.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "switchyard.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  routes.toml: |
{{ .Values.routesToml | nindent 4 }}
  .env: |
{{- range .Values.providers }}
{{- if .secret }}
    {{ .envVar }}='{{ (lookup "v1" "Secret" $.Release.Namespace .secret).data (default "token" .secretKey) | default "" | b64dec }}'
{{- else }}
    {{ .envVar }}=''
{{- end }}
{{- end }}